 spring.datasource.url=jdbc:postgresql://localhost:5432/vanancy-management
 spring.datasource.username=admin
 spring.datasource.password=admin
 spring.jpa.hibernate.ddl-auto=update

security.token.secret=JAVAGAS238574352roerpgvc
security.token.secret.candidate= 2u3irygh89273y592e7y2918jkdf